---
# tasks file for redhatnordicssa.yum_gpgcheck
- name: Find yum repository files
  ansible.builtin.command: find /etc/yum.repos.d -type f
  register: repo_files

- name: Print list of repo files we will manage
  debug:
    msg: "{{ repo_files.stdout }}"
    verbosity: 2

- name: "Ensure gpgcheck is enabled on all found repositories"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '(.*)gpgcheck.*'
    replace: 'gpgcheck = 1'
  with_items: "{{ repo_files.stdout_lines }}"

- name: "Ensure gpgcheck defaults to true"
  ansible.builtin.replace:
    path: /etc/yum.conf
    regexp: '(.*)gpgcheck.*'
    replace: 'gpgcheck=1'

- name: "Enable gpgcheck by default if missing"
  ansible.builtin.lineinfile:
    path: /etc/yum.conf
    line: 'gpgcheck=1'
